swagger: '2.0'

info:
  version: "0.1.0"
  title: PistachoBizi API

host: recu.synology.me:8080
basePath: /bizi/api

schemes: 
  - http

paths:

  /towns:

    get:

      description: |
        Gets `Town` objects.
      produces: 
      - application/json

      responses:

        200:
          description: Successful response
          schema:
            title: towns
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                town:
                  type: string
  /weather/{townId}/{envelope}:
    get:
      description: |
        Gests weather for given `townId` inside specified `envelope`
      parameters: 
        - name: townId
          in: path
          description: the town ID according to Spain
          required: true
          type: integer
          minimum: 50001
          maximum: 50298
        - name: envelope
          in: path
          description: the envelope in which weather must be requested 
                        either JSON or XML
          required: true
          type: string
          enum: [ "JSON", "XML" ]
      produces:
      - text/html
      responses:
        200:
          description: Successful response

